/* eslint-disable @next/next/no-html-link-for-pages */
import styles from "./vibe-coding.module.css";

const screenshots = {
  home: "/images/vibe-coding/Snipaste_2026-09-12_02-41-10.png",
  work: "/images/vibe-coding/Snipaste_2026-09-12_02-43-08.png",
  about: "/images/vibe-coding/Snipaste_2026-09-12_02-43-40.png",
  playground: "/images/vibe-coding/Snipaste_2026-09-12_02-43-54.png",
  caseStudy: "/images/vibe-coding/Snipaste_2026-09-12_02-44-03.png",
  detail: "/images/vibe-coding/Snipaste_2026-09-12_02-44-12.png",
};

const references = [
  ["/images/vibe-coding/references/ref-01-color-playfulness.jpg.jpg", "COLOR / PLAYFULNESS"],
  ["/images/vibe-coding/references/ref-02-editorial-folders.jpg.jpg", "EDITORIAL / TYPE"],
  ["/images/vibe-coding/references/ref-03-scrapbook-commerce.jpg.jpg", "FOLDER / STRUCTURE"],
  ["/images/vibe-coding/references/ref-04-grid-details.jpg.jpg", "GRID / DETAILS"],
];

export default function VibeCodingPage() {
  return <main className={styles.page}>
    <nav className="nav" aria-label="Main navigation"><a className="wordmark" href="/">REMI&apos;S CREATIVE DESK</a><div className="nav-links"><a href="/#work">WORK</a><a href="/#about">ABOUT</a><a href="/#playground">PLAYGROUND</a><a href="/#contact">CONTACT</a></div></nav>
    <section className={`${styles.hero} paper-grid`}><a className={styles.back} href="/#playground">← BACK TO PLAYGROUND</a><div className={styles.meta}><span>PLAYGROUND / 02</span><span>VIBE CODING</span><span>2026</span></div><div className={styles.heroGrid}><div><h1>FROM TASTE<br />TO A <em>WORKING</em><br />WEBSITE.</h1><p className={styles.lead}>I started with references, a feeling and a rough idea of how I wanted the portfolio to behave — then used AI-assisted coding to turn that direction into a working website.</p><p className={styles.cn}>我不是从代码开始，<br />而是从视觉参考、内容结构和“我希望它给人什么感觉”开始。<br />再借助 AI 辅助编程，把这些判断一步步变成真正可以浏览的网站。</p></div><figure className={styles.heroShot}><img src={screenshots.home} alt="Final portfolio homepage" /><figcaption>FINAL HOMEPAGE / 2026</figcaption></figure></div><aside className={styles.buildNote}>AI-ASSISTED BUILD /<br /><b>HUMAN-DIRECTED</b></aside></section>
    <section className={styles.references}><p className={styles.label}>01 / COLLECTING CLUES</p><div className={styles.referenceIntro}><h2>I WASN&apos;T<br />LOOKING FOR<br />A TEMPLATE.<br />I WAS<br /><em>COLLECTING<br />CLUES.</em></h2><div><p>I was drawn to different things in different references — playful color, editorial typography, folder-like structures, paper textures and small imperfect details.</p><p className={styles.cn}>我并不是想找到一个网站直接照着做。<br />真正吸引我的，是不同参考里各自成立的部分：<br />配色、字体层级、纸张感、档案结构，以及一点不那么规整的手作感。</p></div></div><div className={styles.moodboard}>{references.map(([src,label], index) => <figure key={src}><img src={src} alt={`Visual reference: ${label}`} /><figcaption>{label}</figcaption></figure>)}</div></section>
    <section className={styles.translation}><p className={styles.label}>02 / CREATIVE DIRECTION</p><h2>TASTE NEEDS<br /><em>TRANSLATION.</em></h2><div className={styles.translationLead}><p>A reference only tells me what I like. The next step was understanding why — and turning those observations into repeatable design decisions.</p><p className={styles.cn}>“喜欢”本身还不能成为设计方向。<br />我需要继续拆解：<br />到底是颜色、字体、结构，还是某种不那么规整的视觉节奏吸引了我，<br />再把这些感觉变成可以反复使用的规则。</p></div><div className={styles.map}><div><b>WHAT I NOTICED</b><span>soft playful color</span><span>editorial hierarchy</span><span>archive / folder structures</span><span>paper &amp; grid textures</span><span>imperfect details</span></div><i aria-hidden="true">→</i><div><b>WHAT IT BECAME</b><span>warm cream base</span><span>dusty pink / powder blue / butter yellow</span><span>expressive serif + clean supporting type</span><span>folder-like project cards</span><span>restrained scrapbook graphics</span><span>grid-paper portfolio system</span></div></div></section>
    <section className={styles.iterate}><p className={styles.label}>03 / BUILD &amp; ITERATE</p><div className={styles.iterateIntro}><h2>THE FIRST<br />ANSWER WAS<br />RARELY THE<br /><em>FINAL ONE.</em></h2><div><p>AI made it faster to turn decisions into something visible. But seeing the page made new problems visible too — hierarchy, image scale, copy, navigation and how real content changed the composition.</p><p className={styles.cn}>AI 让我更快看到一个想法真正落到页面上的样子，<br />但页面出现以后，新的判断才开始：<br />图片够不够有力量？信息层级是否清楚？<br />真实内容放进去以后，原来的版式还成立吗？<br />哪些东西应该留下，哪些应该删掉？</p></div></div><div className={styles.process}><span>STRUCTURE</span><b>→</b><span>REAL CONTENT</span><b>→</b><span>REVIEW</span><b>→</b><span>REFINE</span></div><div className={styles.iterateShots}><figure><img src={screenshots.work} alt="Selected Work page during the final portfolio build" /><figcaption>HIERARCHY / REAL IMAGERY</figcaption></figure><figure><img src={screenshots.caseStudy} alt="Case study layout in the final portfolio" /><figcaption>COPY / NAVIGATION / RESPONSIVE QA</figcaption></figure><figure><img src={screenshots.detail} alt="Portfolio detail view" /><figcaption>CONSISTENCY</figcaption></figure></div></section>
    <section className={styles.result}><p className={styles.label}>04 / THE RESULT</p><div className={styles.resultIntro}><h2>ONE SYSTEM.<br />DIFFERENT<br /><em>STORIES.</em></h2><div><p>The final portfolio needed to hold commercial work, visual storytelling and personal experiments without making them feel like separate identities.</p><p className={styles.cn}>最后我想解决的并不只是“做一个好看的网页”。<br /><br />它需要同时容纳商业项目、消费者洞察、视觉内容和个人实验，<br />但依然让人感觉它们来自同一个人、同一套视觉语言。</p></div></div><div className={styles.resultCollage}><figure className={styles.resultMain}><img src={screenshots.about} alt="About section in the final portfolio" /></figure><figure className={styles.resultA}><img src={screenshots.playground} alt="Creative Playground in the final portfolio" /></figure><figure className={styles.resultB}><img src={screenshots.home} alt="Homepage in the final portfolio" /></figure><span>CONTENT × BRAND × VISUAL × AI-ASSISTED MAKING</span></div></section>
    <section className={styles.reflection}><p className={styles.label}>05 / REFLECTION</p><h2>AI CAN MAKE<br />THINGS FASTER.<br />DIRECTION<br />STILL NEEDS<br />A <em>HUMAN.</em></h2><p className={styles.italic}>The tool helped me make it.<br />The decisions made it mine.</p><div className={styles.reflectionCopy}><p>This project changed how I think about making digital work.<br /><br />I don&apos;t need to begin with perfect technical knowledge to test an idea. But I do need to know what I am trying to communicate, what feels right, what feels generic, and when something needs another pass.<br /><br />AI shortened the distance between an idea and a working result. It did not remove the need for taste, structure or judgment.</p><p className={styles.cn}>这个项目让我重新理解了“把想法做出来”这件事。<br /><br />我不需要先成为专业开发者，才能验证一个数字产品的想法。<br />但我仍然需要判断：<br />我到底想表达什么，<br />什么是适合这个项目的，<br />什么看起来过于模板化，<br />以及什么时候还需要再改一次。<br /><br />AI 缩短了想法与成品之间的距离，<br />但没有替代审美、结构和判断。</p></div><div className={styles.path}><span>REFERENCE</span><b>→</b><span>DIRECTION</span><b>→</b><span>BUILD</span><b>→</b><span>REVIEW</span><b>→</b><span>REFINE</span></div><a className={styles.return} href="/#playground">← CREATIVE PLAYGROUND</a></section>
  </main>;
}
