import Link from "next/link";
import Image from "next/image";
import styles from "./page.module.css";
import strategyPolish from "./strategy-polish.module.css";
import visualDesign from "./visual-design.module.css";
import "./visual-polish.module.css";
import "./impact.module.css";
import "./recognition.module.css";
import "./reflection.module.css";
import "./qa-polish.module.css";

const image = (name: string) => `/images/consumer-brand/${name.includes(".") ? name : `${name}.svg`}`;

export default function ConsumerBrandCaseStudy() {
  return <main className={`case-study ${styles.page}`}>
    <nav className="nav"><Link className="wordmark" href="/">REMI&apos;S CREATIVE DESK</Link><div className="nav-links"><Link href="/#work">WORK</Link><Link href="/#about">ABOUT</Link><Link href="/#playground">PLAYGROUND</Link><Link href="/#contact">CONTACT</Link></div></nav>
    <section className="case-cover paper-grid"><Link className="back-link" href="/#work">← BACK TO WORK</Link><p className="case-label">01 / CONSUMER GROWTH · UK</p><div className="cover-grid"><div><div className="case-meta"><span>ROLE<br /><b>E-COMMERCE OPERATIONS</b></span><span>MARKET<br /><b>UK</b></span><span>CATEGORY<br /><b>KIDS &amp; FAMILY</b></span><span>CHANNEL<br /><b>ETSY</b></span></div><h1>BUILDING A<br />CONSUMER BRAND</h1><p className="case-cn">从 0 到 1 打造英国母婴消费品店铺</p><p className="case-lead">From consumer insight to visual storytelling —<br />building products UK families wanted to make their own.</p><p className="hero-proof">14.4K+ ORDERS · ¥1.61M+ 2025 GMV · 10+ ETSY&apos;S PICKS</p></div><div className="cover-image"><img loading="eager" fetchPriority="high" decoding="async" src={image("01 COVER.webp")} alt="Consumer brand cover" /><span>UK MARKET</span><i>KIDS &amp; FAMILY</i><b>0 → 1</b></div></div></section>
    <section className="case-section challenge"><p className="case-label">02 / THE CHALLENGE</p><h2>IT STARTED WITH<br />ONE QUESTION.</h2><div className="challenge-grid"><p className="case-question">How can an unknown product<br />become something UK families<br />actually want?</p><div><p className="case-cn">面对没有品牌认知的新品，我需要解决的不只是“怎么卖出去”，而是先理解：谁会购买、为什么购买，以及什么样的产品与内容能够让消费者产生连接。</p><aside className="project-note"><strong>PROJECT NOTE</strong><span>MARKET <b>UK</b></span><span>CATEGORY <b>KIDS &amp; FAMILY</b></span><span>CHANNEL <b>ETSY</b></span><span>ROLE <b>E-COMMERCE OPERATIONS</b></span><span>SCOPE <b>0 → 1</b></span></aside></div></div></section>
    <section className="case-section insights paper-grid"><p className="case-label">03 / CONSUMER INSIGHT</p><h2>NOT JUST<br />A BACKPACK.</h2><p className="case-lead">What parents were really buying into:</p><div className="research-board"><img loading="lazy" decoding="async" className="slot product" src={image("02 PRODUCT.webp")} alt="Personalized product" /><article className="insight-note"><b>PERSONALIZATION</b><em>&quot;This one is hers.&quot;</em><p>姓名定制带来的专属感。</p></article><img loading="lazy" decoding="async" className="slot lifestyle" src={image("03 LIFESTYLE.webp")} alt="Lifestyle scene" /><article className="insight-note yellow"><b>BACK-TO-SCHOOL</b><em>A small ritual for a big new chapter.</em><p>开学不仅是功能需求，也是家庭消费的重要节点。</p></article><img loading="lazy" decoding="async" className="slot parent" src={image("04 PARENT-CHILD.webp")} alt="Parent and child scene" /><article className="insight-note sage"><b>EMOTIONAL VALUE</b><em>Something worth remembering.</em><p>家长希望产品同时具有礼物感和成长纪念意义。</p></article><p className="insight-source"><b>SIGNALS I USED</b><span>CUSTOMER REVIEWS · PERSONALIZATION REQUESTS · SALES PATTERNS · COMPETITOR LISTINGS</span></p></div></section>
    <section className={`case-section strategy ${strategyPolish.polish}`}><p className="case-label">04 / STRATEGY</p><h2>FROM INSIGHT<br />TO CONTENT.</h2><p className="strategy-intro">I translated consumer signals into product,<br />visual and content decisions — connecting<br />what families cared about with how the<br />product was presented and sold.</p><p className="strategy-scope">WITHIN E-COMMERCE OPERATIONS</p><div className="strategy-map">{[{number:"01",title:"CONSUMER\nINSIGHT",details:["UK young families","Personalization","Back-to-school moments","Emotional value"]},{number:"02",title:"PRODUCT\nPOSITIONING",details:["Personalized kids essentials","Practical + emotional","Made to feel uniquely theirs"]},{number:"03",title:"VISUAL\nDIRECTION",details:["Soft","Natural","Minimal","Warm"]},{number:"04",title:"CONTENT\nSCENARIOS",details:["School","Family","Outdoor","Everyday life"]},{number:"05",title:"CONVERSION",details:["Personalization","Size & capacity","Styling","Add-ons"]}].map((stage,index)=><div className="strategy-stage" key={stage.number}><span className="stage-number">{stage.number}</span><h3>{stage.title.split("\n").map(line=><span key={line}>{line}</span>)}</h3><ul>{stage.details.map(detail=><li key={detail}>{detail}</li>)}</ul>{index < 4 && <i className="stage-arrow" aria-hidden="true">→</i>}</div>)}</div><p className="strategy-note">WHAT PEOPLE CARE ABOUT <b>→</b> WHAT WE CREATE <b>→</b> HOW WE PRESENT IT <b>→</b> WHY THEY CHOOSE IT</p></section>
    <section className={`case-section visuals paper-grid ${visualDesign.visuals}`}><p className="case-label">05 / CONTENT &amp; VISUAL</p><h2>MAKE IT<br />FEEL REAL.</h2><p className="case-lead">Product content shouldn&apos;t only show what something looks like.<br />It should help people imagine where it belongs.</p><div className="lifestyle-composition"><div className="lifestyle-hero"><Image src={image("05-hero.png.webp")} alt="Girl with a pink personalized backpack by a window" fill sizes="(max-width: 800px) 92vw, 52vw" priority /></div><div className="lifestyle-family"><Image src={image("05-family.png.webp")} alt="Family everyday moment" fill sizes="(max-width: 800px) 60vw, 26vw" /></div><div className="lifestyle-play"><Image src={image("05-play.png.webp")} alt="Play interaction" fill sizes="(max-width: 800px) 55vw, 21vw" /></div><span className="caption-moments">EVERYDAY MOMENTS ↗</span><span className="caption-family">FAMILY</span><span className="caption-play">PLAY</span></div><p className="life-statement">FROM SHOWING A PRODUCT<br />TO SHOWING A LIFE AROUND IT.</p><div className="system-transition"><p className="case-label">BEYOND A SINGLE IMAGE</p><h3>FROM ONE PRODUCT<br />TO A VISUAL SYSTEM.</h3><p>The same visual language was carried across<br />products, colors and personalized variations —<br />building a more recognizable and consistent<br />shopping experience.</p></div><div className="system-sheet"><div className="system-product"><Image src={image("05-product-system.png.webp")} alt="Product visual direction" fill sizes="(max-width: 800px) 92vw, 46vw" /><span>PRODUCT IN CONTEXT</span></div><div className="system-range"><Image src={image("05-range.png.webp")} alt="Product range and personalization" fill sizes="(max-width: 800px) 92vw, 50vw" /><span>PRODUCT RANGE</span></div><div className="system-detail"><Image src={image("05-detail.jpg.webp")} alt="Product detail and assortment" fill sizes="(max-width: 800px) 60vw, 24vw" /></div><span className="detail-caption">DETAIL / ASSORTMENT</span><p className="system-statement">ONE VISUAL LANGUAGE,<br />MULTIPLE PRODUCTS &amp; MOMENTS.</p><i>CONSISTENCY</i></div></section>
    <section className="case-section impact"><p className="case-label">06 / IMPACT</p><p className="impact-kicker">SO, DID IT WORK?</p><h2>CREATIVE IN A<br />GROWING BUSINESS.</h2><p className="impact-note">FROM 0 → 1<br />TO SUSTAINED GROWTH.</p><div className="impact-numbers">{[["14.4K+","ORDERS"],["¥1.61M+","2025 GMV"],["110+","PEAK DAILY ORDERS"],["10+","ETSY'S PICKS"]].map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><p className="impact-transition">BUT NUMBERS WERE ONLY<br />PART OF THE STORY.<span>↓</span><b>SELECTED BY ETSY</b></p></section>
    <section className="case-section etsy paper-grid"><p className="case-label">07 / PLATFORM RECOGNITION</p><h2>SELECTED<br />BY ETSY.</h2><p className="case-lead">10+ Etsy&apos;s Picks across products,<br />categories &amp; seasonal moments.</p><div className="recognition-wall"><div className="recognition-image recognition-hero"><Image src={image("07-pick-02.png.webp")} alt="Two children with backpacks selected by Etsy" fill sizes="(max-width: 800px) 92vw, 46vw" priority /><i>ETSY&apos;S PICK ✦</i></div><div className="recognition-image recognition-core"><Image src={image("07-pick-01.png.webp")} alt="Three personalized backpacks selected by Etsy" fill sizes="(max-width: 800px) 70vw, 28vw" /></div><div className="recognition-image recognition-easter"><Image src={image("07-pick-03.png.webp")} alt="Easter basket selected by Etsy" fill sizes="(max-width: 800px) 65vw, 24vw" /><i>ETSY&apos;S PICK ✦</i></div><div className="recognition-image recognition-home"><Image src={image("07-pick-06.png.webp")} alt="Home pillow scene selected by Etsy" fill sizes="(max-width: 800px) 72vw, 31vw" /></div><div className="recognition-image recognition-halloween"><Image src={image("07-pick-04.png.webp")} alt="Halloween item selected by Etsy" fill sizes="(max-width: 800px) 50vw, 16vw" /></div><div className="recognition-image recognition-christmas"><Image src={image("07-pick-05.png.webp")} alt="Christmas item selected by Etsy" fill sizes="(max-width: 800px) 50vw, 16vw" /></div><div className="recognition-image recognition-pet"><Image src={image("07-pick-07.png.webp")} alt="Pet basket selected by Etsy" fill sizes="(max-width: 800px) 58vw, 20vw" /></div><span className="recognition-label label-kids">KIDS &amp; FAMILY</span><span className="recognition-label label-seasonal">SEASONAL</span><span className="recognition-label label-home">HOME</span><span className="recognition-label label-personal">PERSONALIZATION</span><p className="recognition-statement">A visual approach that worked<br />across products &amp; moments.</p></div><p className="recognition-close">RECOGNITION IS NICE.<br />REPEATABILITY MATTERS MORE.<span>↓</span></p></section>
    <section className="case-section reflection"><div className="reflection-grid"><div><p className="case-label">08 / WHAT I LEARNED</p><h2>GOOD CONTENT<br />DOESN&apos;T START<br />WITH A CAMERA.</h2></div><div className="reflection-content"><p className="reflection-lead">It starts with understanding<br /><em>what people care about.</em></p><p className="case-cn">对我来说，内容不是产品完成后的包装，<br />而是从消费者洞察开始，<br />参与产品定位、视觉表达与消费场景的建立。</p><p className="method-line">INSIGHT → POSITIONING → CONTENT → CONNECTION</p></div></div><Link className="next-case" href="/work/easter-moment"><span>NEXT CASE ↗</span><strong>DESIGNING AN<br />EASTER MOMENT</strong><small>SEASONAL CAMPAIGN / EMOTIONAL COMMERCE</small><i>→</i></Link></section>
  </main>;
}
