const projects = [
  { tab: "01 / E-COMMERCE × BRAND", title: "BUILDING A\nCONSUMER BRAND", subtitle: "从 0 到 1 打造英国母婴消费品牌", description: "From consumer insight and product positioning\nto visual storytelling and commercial growth.", tags: ["CONSUMER INSIGHT", "BRAND DIRECTION", "CONTENT STRATEGY", "E-COMMERCE"], color: "archive-cream", href: "/work/consumer-brand", imageSrc: "/images/consumer-brand/01%20COVER.jpg", imageAlt: "Child wearing a personalized backpack for the Consumer Brand case study", imagePosition: "center", supportImages: [{ src: "/images/consumer-brand/02%20PRODUCT.png", alt: "Personalized product detail" }, { src: "/images/consumer-brand/04%20PARENT-CHILD.png", alt: "Parent and child using a personalized product" }], results: [["14,400+", "ORDERS"], ["¥1.61M+", "GMV"], ["110+", "PEAK DAILY ORDERS"], ["10+", "ETSY'S PICKS"]] },
  { tab: "02 / SEASONAL CAMPAIGN", title: "DESIGNING AN\nEASTER MOMENT", subtitle: "把节日商品变成消费者想参与的情绪体验", description: "Turning seasonal demand into\nvisual atmosphere, emotion and content.", tags: ["SEASONAL CAMPAIGN", "CONSUMER INSIGHT", "VISUAL DIRECTION", "CONTENT"], color: "archive-pink", href: "/work/easter-moment", imageSrc: "/images/easter-moment/easter-01-cover.png", imageAlt: "Girl holding a personalized Easter basket", imagePosition: "center" },
  { tab: "03 / CONTENT & VISUAL", title: "VISUAL\nSTORYTELLING", subtitle: "让产品进入真实生活场景，而不只是被展示", description: "Using product photography, AI-assisted visuals\nand lifestyle scenes to help consumers imagine the product in their lives.", tags: ["VISUAL DIRECTION", "CONTENT", "AI VISUAL", "PRODUCT STORYTELLING"], color: "archive-blue", href: "/work/visual-storytelling", imageSrc: "/images/visual-storytelling/visual-01-outdoor.png", imageAlt: "Personalized product shown in an outdoor lifestyle setting", imagePosition: "center" },
];

export default function Home() {
  return <main>
    <nav className="nav" aria-label="Main navigation"><a className="wordmark" href="#top">REMI&apos;S CREATIVE DESK</a><div className="nav-links"><a href="#work">WORK</a><a href="#about">ABOUT</a><a href="#playground">PLAYGROUND</a><a href="#contact">CONTACT</a></div></nav>
    <section className="hero paper-grid" id="top">
      <div className="hero-copy reveal"><p className="hero-desk-label">REMI&apos;S CREATIVE DESK</p><p className="hero-role">CONTENT / BRAND / VISUAL</p><div className="hero-title"><p>REMI&apos;S</p><p>CREATIVE</p><p className="hero-title-last"><em>PORTFOLIO</em></p></div><p className="hero-statement">I follow what people notice, want and choose —<br />then turn it into content, visuals and products that connect.</p></div>
      <div className="hero-collage reveal" aria-label="Seasonal and lifestyle project collage"><figure className="hero-photo hero-photo-main"><img src="/images/easter-moment/easter-04-lifestyle.png" alt="Child using a personalized Easter basket outdoors" /><i aria-hidden="true" /></figure><figure className="hero-photo hero-photo-support"><img src="/images/visual-storytelling/visual-02-lifestyle.png" alt="Lifestyle product visual" /></figure><figure className="hero-photo hero-photo-third" style={{ width: "32%", height: "30%", right: "-1%", top: "4%", transform: "rotate(-4deg)", zIndex: 4 }}><img src="/images/easter-moment/easter-07-product.png" alt="Seasonal product presentation" /></figure><p className="hero-proof">14.4K+ ORDERS<br />10+ ETSY&apos;S PICKS</p><span className="hero-collage-arrow" aria-hidden="true">↗</span></div>
    </section>
    <div className="marquee" aria-label="Portfolio disciplines"><span>CONSUMER INSIGHT</span><b>✦</b><span>CONTENT STRATEGY</span><b>✦</b><span>VISUAL STORYTELLING</span><b>✦</b><span>COMMERCIAL THINKING</span></div>
    <section className="work-section" id="work"><div className="section-heading archive-heading reveal"><p className="eyebrow">01 / SELECTED WORK</p><h1>A FEW THINGS<br />I&apos;VE SHAPED<br /><em>&amp; GROWN.</em></h1><p className="section-subtitle">一些关于消费者、内容、视觉与增长的实践。</p></div><div className="project-list archive-list">
      {projects.map((project, index) => <article className={`project-file ${project.color} archive-file ${index === 0 ? "project-one" : ""} reveal`} key={project.tab}><div className="folder-tab">{project.tab}</div><span className="paperclip" aria-hidden="true">⌇</span><span className="file-note" aria-hidden="true">ARCHIVE / 0{index + 1}</span><div className="project-copy"><p className="project-number">PROJECT FILE / 2026</p><h2>{project.title.split("\n").map((line) => <span key={line}>{line}</span>)}</h2><p className="chinese">{project.subtitle}</p><p className="project-description">{project.description.split("\n").map((line) => <span key={line}>{line}</span>)}</p><div className="tag-list">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>{project.results && <div className="results">{project.results.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>}<a className="project-link" href={project.href}>VIEW FULL CASE <span aria-hidden="true">↗</span></a></div>{index === 0 ? <div className="project-one-images"><div className="project-image project-one-main"><img src={project.imageSrc} alt={project.imageAlt} style={{ objectPosition: project.imagePosition }} /><i className="tape" aria-hidden="true" /></div><img className="project-one-support family-shot" src={project.supportImages?.[1].src} alt={project.supportImages?.[1].alt} /><span className="project-one-note" style={{ right: "17%", bottom: "16%" }}>FROM 0 → 1</span></div> : <div className="project-image"><img src={project.imageSrc} alt={project.imageAlt} style={{ objectPosition: project.imagePosition }} /><i className="tape" aria-hidden="true" /></div>}<a className="card-click-overlay" href={project.href} aria-label={`View full case study: ${project.title.replace("\n", " ")}`} /></article>)}
    </div></section>
    <section className="career-note paper-grid" id="about"><div className="career-note-top"><div className="career-statement reveal"><p className="eyebrow">02 / ABOUT</p><h1>I STARTED IN<br />E-COMMERCE.<br />I KEPT FOLLOWING<br /><span>THE PEOPLE.</span></h1></div><div className="career-intro reveal"><p className="career-kicker">DESK NOTE / CAREER DIRECTION</p><p>I&apos;m Remi, an e-commerce operator bringing consumer, content and visual thinking into my next chapter in Content &amp; Brand Marketing.</p><p>Working on overseas consumer products taught me to look beyond listings and conversion — toward the people choosing them, the moments they buy for, and the stories that make products feel relevant.</p><p className="career-cn">我从跨境电商运营出发，在英国消费者与母婴品类的实际经营中，<br />逐渐把工作延伸到消费者洞察、产品表达、视觉内容与场景化沟通。</p><p className="career-cn">下一步，我希望把这些来自真实商业场景的经验，<br />带进 Content &amp; Brand Marketing。</p><i>still curious.</i></div></div><div className="career-thread"><span>E-COMMERCE</span><b>→</b><span>CONSUMER INSIGHT</span><b>→</b><span>CONTENT</span><b>→</b><span>BRAND</span></div></section>
    <section className="playground paper-grid" id="playground"><div className="section-heading reveal"><p className="eyebrow">OFF THE CLOCK / ON THE DESK</p><h1>CREATIVE PLAYGROUND</h1><p className="section-subtitle">Things I make when curiosity takes over.</p></div><div className="play-items reveal"><a className="play-item photo-one" href="/playground/ai-visual-experiments"><span>01</span><strong>AI Visual<br />Experiments</strong></a><div className="play-item note"><span>02</span><strong>Campaign<br />Concepts</strong><i>What if?</i></div><a className="play-item photo-two" href="/playground/vibe-coding"><span>03</span><strong>Vibe Coding</strong></a><div className="play-item ticket"><span>04</span><strong>Personal<br />Projects</strong></div></div></section>
    <footer id="contact"><p className="eyebrow">SAY HELLO / DON&apos;T BE A STRANGER</p><h1>LET&apos;S MAKE<br />SOMETHING<br /><em>WORTH NOTICING.</em></h1><div className="footer-bottom"><a href="mailto:15099913150@163.com">EMAIL ↗</a><span className="contact-availability">WECHAT / AVAILABLE ON REQUEST</span><span>© 2026 REMI</span></div></footer>
  </main>;
}
